-- SALES ANALYSIS --

-- What is the total revenue generated by the company?
SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM order_payments;

-- How many orders have been placed?
SELECT 
	COUNT(*) as Total_orders
FROM orders;

-- How many unique customers have purchased?
SELECT
	COUNT(DISTINCT customer_id) AS Total_Customers
FROM customers;


-- On average, how much does a customer spend per order?
SELECT
    ROUND(AVG(order_total), 2) AS average_order_value
FROM (
    SELECT
        order_id,
        SUM(payment_value) AS order_total
    FROM order_payments
    GROUP BY order_id
) AS order_summary;

-- How has revenue changed month by month?
SELECT
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    ROUND(SUM(p.payment_value), 2) AS revenue
FROM orders o
JOIN order_payments p
    ON o.order_id = p.order_id
GROUP BY month
ORDER BY month;

-- How many orders were placed each month?
SELECT
    DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY month
ORDER BY month;

-- Which months generated the highest revenue?
SELECT
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    ROUND(SUM(p.payment_value),2) AS revenue
FROM orders o
JOIN order_payments p
ON o.order_id = p.order_id
GROUP BY month
ORDER BY revenue DESC;

-- Which payment method contributes the most revenue?
SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS revenue
FROM order_payments
GROUP BY payment_type
ORDER BY revenue DESC;

-- What is the average payment amount for each payment method?
SELECT
    payment_type,
    ROUND(AVG(payment_value),2) AS average_payment
FROM order_payments
GROUP BY payment_type
ORDER BY average_payment DESC;

-- What percentage of total revenue comes from each payment method?
SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS revenue,
    ROUND(
        SUM(payment_value) * 100 /
        (SELECT SUM(payment_value) FROM order_payments),
        2
    ) AS revenue_percentage
FROM order_payments
GROUP BY payment_type
ORDER BY revenue DESC;

